name=input("enter your   name")
while name == "":
    print("you didn't enter a name, you must enter a name to continue")
    name=input("enter your   name")
print(f"hello {name}")
age=input("enter your age")
print(f"your age is{age}")
color=("green")
print(f"your favorite color is {color}")
sport=("skiing")
drink=("hot chocklit")
print(f"I love {sport} and I like to have {drink} when I come in for a warmup")